waypoints: # URC2025 GPS Waypoints Starts:38.41910142, -110.782723
- latitude: 38.204249
  longitude: 140.861932
  yaw: 0.0
  spiral_search: true
  aruco: enable
  marker_id: 2
  yolo: disable
  
- latitude: 38.204037
  longitude: 140.860978
  yaw: 0.0
  spiral_search: true
  aruco: enable
  marker_id: 3
  yolo: disable
  
- latitude: 38.203842
  longitude: 140.859905
  yaw: 0.0
  spiral_search: true
  aruco: disable
  marker_id: 1
  yolo: mallet
  
- latitude: 38.203169
  longitude: 140.859164
  yaw: 0.0
  spiral_search: true
  aruco: disable
  marker_id: 1
  yolo: hammer

- latitude: 38.203312
  longitude: 140.858500
  yaw: 0.0
  spiral_search: true
  aruco: disable
  marker_id: 1
  yolo: bottle
