waypoints: # URC2025 GPS Waypoints Starts:38.41910142, -110.782723
- latitude: 38.204509
  longitude: 140.863009
  yaw: 0.0
  spiral_search: false
  aruco: disable
  marker_id: 3
  yolo: disable

- latitude: 38.204637
  longitude: 140.862586
  yaw: 0.0
  spiral_search: false
  aruco: disable
  marker_id: 3
  yolo: disable

- latitude: 38.204321
  longitude: 140.862150
  yaw: 0.0
  spiral_search: true
  aruco: enable
  marker_id: 2
  yolo: disable
  
- latitude: 38.204103
  longitude: 140.861352
  yaw: 0.0
  spiral_search: true
  aruco: enable
  marker_id: 3
  yolo: disable
  
- latitude: 38.203765
  longitude: 140.860872
  yaw: 0.0
  spiral_search: true
  aruco: disable
  marker_id: 3
  yolo: mallet
  
- latitude: 38.203679
  longitude: 140.860143
  yaw: 0.0
  spiral_search: true
  aruco: disable
  marker_id: 3
  yolo: hammer

- latitude: 38.203721
  longitude: 140.859556
  yaw: 0.0
  spiral_search: true
  aruco: disable
  marker_id: 3
  yolo: bottle
